@startuml seq_diagram_1.png
participant client1
participant store1

client1 -> store1
store1 -> client1
@enduml

@startuml seq_diagram_2.png
participant client2
participant store2

client2 -> store2 : "place order"
store2 -> client2 : "works"
@enduml
