@startuml usecase_diagram_ver_2.png
actor konrad
actor hania
actor gosia

usecase "Placing an order for fries" as buying
usecase "I am a baker..." as tell_joke
usecase "Fun, meaning good time" as fun_activity

note right of konrad : Yes, Pawlik

konrad --> tell_joke
konrad --> buying
hania --> tell_joke
gosia --> fun_activity
hania --> fun_activity
@enduml
